version: '3.7'

services:

  db_dev:
    image: postgis/postgis:12-master
    env_file:
      - ./.env.dev

  redis_dev:
    build:
      context: ./compose/redis
    image: broker
    command: sh -c "./init.sh"
    ports:
      - "6379:6379"
      
  develop:
    build: ./framework
    image: 'nabla:dev'
    working_dir: /usr/src/framework
    volumes:
      - ./framework/:/usr/src/framework/
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - ENTRY=development
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db_dev
      - redis_dev


